### ISSUE TITLE
Error during MFX decoding

### ISSUE THREAD

**Issue by Z--EN** [intel/gstreamer-media-SDK#116]
Hi Guys, I have error: 

0:00:58.376144969  2255 0x7f4518002940 ERROR                    mfx gstmfxdecoder.c:821:gst_mfx_decoder_decode: Status -17 : Error during MFX decoding

Full Log:

0:00:58.193838250  2255 0x7f4518002940 INFO                     mfx gstmfxtaskaggregator.c:129:gst_mfx_task_aggregator_init_session_context: Using Media SDK API version 1.27
0:00:58.193851285  2255 0x7f4518002940 INFO                     mfx gstmfxtaskaggregator.c:147:gst_mfx_task_aggregator_init_session_context: Initialized internal MFX session using hardware accelerated implementation
0:00:58.193868694  2255 0x7f4518002940 DEBUG                    mfx gstmfxdisplay.c:308:gst_mfx_display_new: creating VAAPI display
libva info: VA-API version 1.2.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_2
libva info: va_openDriver() returns 0
0:00:58.194697735  2255 0x7f4518002940 DEBUG                    mfx gstmfxdisplay.c:219:gst_mfx_display_init_vaapi: VA-API version 1.2
0:00:58.194728933  2255 0x7f4518002940 FIXME           videodecoder gstvideodecoder.c:1057:gst_video_decoder_drain_out:<mfxdec_h264-0> Sub-class should implement drain()
0:00:58.195135578  2255 0x7f4518002940 DEBUG              mfxdecode gstmfxdec.c:270:gst_mfxdec_negotiate:<mfxdec_h264-0> Input codec state changed, renegotiating
0:00:58.195177388  2255 0x7f4518002940 INFO               mfxdecode gstmfxdec.c:251:gst_mfxdec_update_src_caps:<mfxdec_h264-0> new src caps = video/x-raw(memory:MFXSurface), format=(string)NV12, width=(int)240, height=(int)160, interlace-mode=(string)progressive, pixel-aspect-ratio=(fraction)1/1, chroma-site=(string)jpeg, colorimetry=(string)bt601, framerate=(fraction)0/1
0:00:58.195607101  2255 0x7f4510032140 FIXME                default gstutils.c:3766:gst_pad_create_stream_id_internal:<appsrc1:src> Creating random stream-id, consider implementing a deterministic way of creating a stream-id
0:00:58.195688509  2255 0x7f4518002940 INFO                     mfx gstmfxpluginbase.c:647:gst_mfx_plugin_base_decide_allocation:<mfxdec_h264-0> No pool. Making a new pool
0:00:58.195905516  2255 0x7f4518002940 INFO                     mfx gstmfxdecoder.c:517:gst_mfx_decoder_start: Initialized MFX decoder using output video memory surfaces
0:00:58.196583171  2255 0x7f4518002940 DEBUG                    mfx gstmfxdecoder.c:797:gst_mfx_decoder_decode: MFXVideoDECODE_DecodeFrameAsync status: 3
0:00:58.196620245  2255 0x7f4518002940 DEBUG                    mfx gstmfxdecoder.c:797:gst_mfx_decoder_decode: MFXVideoDECODE_DecodeFrameAsync status: -10
0:00:58.273856787  2255 0x7f4518002940 DEBUG                    mfx gstmfxdecoder.c:797:gst_mfx_decoder_decode: MFXVideoDECODE_DecodeFrameAsync status: -10
0:00:58.274233696  2255 0x7f4518002940 DEBUG                    mfx gstmfxdecoder.c:797:gst_mfx_decoder_decode: MFXVideoDECODE_DecodeFrameAsync status: -10
0:00:58.375188316  2255 0x7f4518002940 DEBUG                    mfx gstmfxdecoder.c:797:gst_mfx_decoder_decode: MFXVideoDECODE_DecodeFrameAsync status: -10
0:00:58.375427726  2255 0x7f4518002940 DEBUG                    mfx gstmfxdecoder.c:797:gst_mfx_decoder_decode: MFXVideoDECODE_DecodeFrameAsync status: -10
0:00:58.376111879  2255 0x7f4518002940 DEBUG                    mfx gstmfxdecoder.c:797:gst_mfx_decoder_decode: MFXVideoDECODE_DecodeFrameAsync status: -17
0:00:58.376144969  2255 0x7f4518002940 ERROR                    mfx gstmfxdecoder.c:821:gst_mfx_decoder_decode: Status -17 : Error during MFX decoding

Ubuntu 16.04, I tried master and topic_linux_and_window branches, Gstreamer 1.8.1

**Comment by Z--EN** [comment]
Stream: rtsp://184.72.239.149/vod/mp4:BigBuckBunny_175k.mov. Do you have ideas?

**Comment by ishmael1985** [comment]
@Z--EN anything new on this?

**Comment by Z--EN** [comment]
Thanks for suggest, I didn’t have time, sorry

**Comment by Z--EN** [comment]
I think we can close because I switched to other library now. If I’ll continue I’ll reopen with pipeline, thanks.
