### ISSUE TITLE
'cmake' step fails when trying to build gstreamer-media-SDK

### ISSUE THREAD

**Issue by bojidartonchev** [intel/gstreamer-media-SDK#130]
Hello,

This is my first time trying to build gstreamer-media-SDK on windows.
I am getting an error after cloning this repo, creating a build folder and running 'cmake'.

This is the error:

```
$ cmake ..
-- Building for: Visual Studio 10 2010
-- The C compiler identification is MSVC 16.0.40219.1
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 10.0/VC/bin/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
CMake Error at cmake/FindMediaSDK.cmake:2 (pkg_check_modules):
  Unknown CMake command "pkg_check_modules".
Call Stack (most recent call first):
  cmake/ProjectConfig.cmake:14 (FindMediaSDK)
  CMakeLists.txt:49 (include)

-- Configuring incomplete, errors occurred!
See also "D:/gstreamer-media-SDK/build/CMakeFiles/CMakeOutput.log".
```
I have latest Intel Media SDK 2018 R1 for Windows installed.

Working on:
Windows 10 Pro x64
Intel(R) Core(TM) i5-7400 CPU @ 3.00GHz

Any help would be appreciated!

Thanks

**Comment by ishmael1985** [comment]
@bojidartonchev you are compiling from the master branch of this repo, which does not support Windows. You should switch to the topic_linux_and_window branch of this repo and build gst-mfx with Meson. Go through the README carefully.

**Comment by ishmael1985** [comment]
Ok, I didn't expect you would use MinGW to build gst-mfx. Last time I tried, I encountered all sorts of linker errors.
Can you use the Visual Studio compiler to build gst-mfx instead?

**Comment by ishmael1985** [comment]
@bojidartonchev ok I am going to check it, meanwhile can you try building from my repo, master branch - https://github.com/ishmael1985/gstreamer-media-SDK

**Comment by bojidartonchev** [comment]
@ishmael1985 I ran another ninja build after the first fail, I think it skipped some steps, but finished successfully. The installation completed successfully, too.
Now, i have access to all of the new plugins and it seems to be working.

Thank you very much for the help.

**Comment by ishmael1985** [comment]
@bojidartonchev that's great to hear. I also thought it was about time that I package a new set of gst-mfx binaries for Windows, without going through the hassle of building the plugins, will post them later in the Releases section. You can try them if you've got the time.
Meanwhile please close this issue since it has been resolved.
