### ISSUE TITLE
MFE Mode via MSDK?

### ISSUE THREAD

**Issue by gabe2004** [intel/gstreamer-media-SDK#133]
Can gstreamer utilize MFE (multi frame encode) mode in MSDK?

**Comment by ishmael1985** [comment]
Yes. Check out the topic_linux_and_window branch or my repo - https://github.com/ishmael1985/gstreamer-media-SDK . You'll see mfxh264enc supports it.

**Comment by ishmael1985** [comment]
@gabe2004 if your question has been answered can you please close this?
