### ISSUE TITLE
gst_mfxsink_set_render_backend fails on Broadwell

### ISSUE THREAD

**Issue by rdgRmCore** [intel/gstreamer-media-SDK#135]
When trying to play back big buck bunny encoded as H264, the following error occurs on a Broadwell CPU. This was after compiling the topic_linux_and_window branch. 

(I am able to transcode and use mfxvpp with a filesink)

gst-launch-1.0 filesrc location=/home/rdg/Videos/test/bbb_sunflower_2160p_60fps_normal.mp4 ! qtdemux ! h264parse ! mfxh264dec ! autovideosink
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
Setting pipeline to PAUSED ...
Pipeline is PREROLLING ...
Got context from element 'mfxsink0': gst.mfx.Aggregator=context, gst.mfx.Aggregator=(GstMfxTaskAggregator)"\(GstMfxTaskAggregator\)\ mfxtaskaggregator1";
libva info: VA-API version 1.4.0
libva info: va_getDriverName() returns 0
libva info: User requested driver 'iHD'
libva info: Trying to open /usr/lib/x86_64-linux-gnu/dri/iHD_drv_video.so
libva info: Found init function __vaDriverInit_1_0
libva info: va_openDriver() returns 0
**

ERROR:../gstreamer-media-SDK/gst/mfx/gstmfxsink.c:671:gst_mfxsink_set_render_backend: code should not be reached

**Comment by ishmael1985** [comment]
sudo apt-get install libxrender-dev then recompile gst-mfx

**Comment by ishmael1985** [comment]
Make sure you satisfy this dependency:

Dependency xrender found: NO
Message: DRI3 renderer will be disabled due to missing required dependencies.

**Comment by rdgRmCore** [comment]
After uninstalling and removing the build directory, I am now able to view the video using the pipeline shown in my first comment.

**Comment by ishmael1985** [comment]
Good to hear. Please close this then.

**Comment by rdgRmCore** [comment]
Do you think a code change should be made so that the program doesn't crash and dump core when this error is reached?

**Comment by ishmael1985** [comment]
Agreed. But then this should be re-filed as a new issue.
I'll look into resolving it if I have the time, but I don't think it's a big deal.

**Comment by rdgRmCore** [comment]
OK.
