### ISSUE TITLE
Will this project build on windows (with meson) ?

### ISSUE THREAD

**Issue by boxerab** [intel/gstreamer-media-SDK#137]

**Comment by ishmael1985** [comment]
Yep.

**Comment by boxerab** [comment]
Thanks. I tried to run meson on the topic branch, and it complained about not finding cc, cl, clang or gcc.
I will try your branch.

**Comment by ishmael1985** [comment]
@boxerab is your issue still there? Please close this then. Try not to use MingW or MSYS2 for building the plugins in Windows, just follow the README and all should be ok.

**Comment by boxerab** [comment]
This works when I open a VIsual Studio command window.
This should be put in the windows README :)
