### ISSUE TITLE
[WINDOWS] playbin: avdec_h264 used instead of mfx h264 decode

### ISSUE THREAD

**Issue by boxerab** [intel/gstreamer-media-SDK#143]
I set the rank to be very high for mfx h264 decode, but playbin is still using avdec_h264.
Is there another way of forcing gstreamer to us mfx plugin ?

**Comment by boxerab** [comment]
I have added the mfx dll to `/lib/gstreamer-1.0` directory, and `gst-inspect` can find the mfx plugin,
but when I add `mfx` to my pipeline, I get the error: no element `mfx`

**Comment by brmarkus** [comment]
"mfx" is the collection, container containing several specific plugins.
Run "gst-inspect-1.0 mfx" and something like the following will be printed, actually listing the plugin names to be used in a pipeline:
  mfxh264dec: MFX H264 decoder
  mfxhevcdec: MFX HEVC decoder
  mfxmpeg2dec: MFX MPEG2 decoder
  mfxvc1dec: MFX VC1 decoder
  mfxvp8dec: MFX VP8 decoder
  mfxvp9dec: MFX VP9 decoder
  mfxjpegdec: MFX JPEG decoder
  mfxdecode: MFX Video Decoder
  mfxvpp: MFX video postprocessing
  mfxsinkelement: MFX sink
  mfxsink: MFX Sink Bin
  mfxh264enc: MFX H.264 encoder
  mfxhevcenc: MFX H.265 encoder
  mfxjpegenc: MFX JPEG encoder
  mfxvc1parse: VC1 parser

According to this issue's title you might want to use "mfxh264dec" in your pipeline.

**Comment by boxerab** [comment]
Thanks, But, I don't see any of these plugins when I run gst-inspect

**Comment by brmarkus** [comment]
What do you see instead when running "gst-inspect-1.0 mfx"?
Instead of copying the MFX DLL, can you do a "make" and "make install"? Not sure what else need to be installed and in place.

**Comment by boxerab** [comment]
Also, when I build the INSTALL project, it installs into
`c:\lib\gstreamer-1.0`  which is the wrong directory

**Comment by boxerab** [comment]
Here is the output from gst-inspect:


c:\Users\aaron\src\gstreamer-media-SDK>gst-inspect-1.0 mfx
Plugin Details:
  Name                     mfx
  Description              MFX encoder/decoder/video post-processing plugins
  Filename                 C:\gstreamer\1.0\loki_x86_64\lib\gstreamer-1.0\gstmfx.dll
  Version                  2.0.2
  License                  LGPL
  Source module            gst_mfx
  Binary package           gst_mfx
  Origin URL               http://www.intel.com


  0 features:

**Comment by boxerab** [comment]
I have gstreamer in a non-standard location, btw

**Comment by brmarkus** [comment]
Ups, didn't know you were building under MS-Windows...
If under Linux I could say something went wrong building the mfx plugins... your output of gst-inspect doesn't show anything but "0 features"...

**Comment by boxerab** [comment]
Perhaps the problem is issue#144

**Comment by ishmael1985** [comment]
Yes it is indeed.
