### ISSUE TITLE
[WINDOWS] Why is there a custom d3d sink ?

### ISSUE THREAD

**Issue by boxerab** [intel/gstreamer-media-SDK#153]
gstreamer already has `d3dvideosink` . Why is there a need for a custom sink ?

**Comment by ph0b** [comment]
d3dvideosink doesn't handle input from video memory, and a few over things such as HDR rendering. 

Being able to run a pipeline without having to transfer decoded video frames back and forth over CPU memory is a quite critical.

That'll certainly be better to have a separate d3d11videosink and a "DX11Memory" input support independently of this project, but until then, that custom sink is needed.

**Comment by boxerab** [comment]
Thanks.
