### ISSUE TITLE
Support for Windows?

### ISSUE THREAD

**Issue by pauldotknopf** [intel/gstreamer-media-SDK#39]
Title says it all.

**Comment by ph0b** [comment]
yes, it's there! in this topic branch at the moment: https://github.com/01org/gstreamer-media-SDK/tree/topic_linux_and_window

**Comment by pauldotknopf** [comment]
Ah, I see! Looks pretty active.

Is it considered stable? Should I expect quarks/issues?

**Comment by ishmael1985** [comment]
As stable as it can be atm :) But please report any issues to us you may find.

**Comment by SiewHoon** [comment]
For window, plrease refer to topic_linux_and_window branch. 
I will closed if you still got issue then re-open back it.
