### ISSUE TITLE
Support for GStreamer 1.12?

### ISSUE THREAD

**Issue by pauldotknopf** [intel/gstreamer-media-SDK#40]
Your documentation says 1.10. Unfortunately, I need 1.12. Any plans to support it?

**Comment by ishmael1985** [comment]
Don't worry, gst-mfx works even on 1.13 :) So it will work on 1.12, we've tested it. In fact, we recommend you use the latest stable 1.12.2.
For Windows,  1.10 is the minimum due mainly to HDR support, Linux you can build it with 1.8.
Please close the issues once you've verified the issues btw.

**Comment by SiewHoon** [comment]
Since you didn't reply back message. I will close it. If you still got issue then re-open back.
