### ISSUE TITLE
H264 multi-stream decode question ?

### ISSUE THREAD

**Issue by araani** [intel/gstreamer-media-SDK#52]
According to the release note 

Intel Atom® SoC E3900 Family, Intel® Celeron® Processor N3350, and Intel® Pentium® Processor N4200 Board Support Package for Yocto Project*—MR3.1 Release (August 2017)
 
3.2.5 Unsupported or discontinued features (p17)
 
**GStreamer VA PI multi-stream decode with H264 not more supported ?????**
 
Is somebody doing multi-stream H264 decoding on Apollo Lake I ???
 
Is this an issue related to the gstreamer-media-SDK

**Comment by ishmael1985** [comment]
Note sure as to why that note is there, but multi-stream H264 decode is working with GST-MFX (gstreamer-media-SDK) on APL-I when I last checked. You could try running multiple H264 decode GStreamer pipelines to see for yourself.

**Comment by SiewHoon** [comment]
Are you still having a problem with running multiple H264 decode stream? Or you are checking info document incorrect? Or can you share the release note that you mention?

**Comment by araani** [comment]
See item 3.2.5 Unsupported or discontinued features 

[partial.pdf](https://github.com/intel/gstreamer-media-SDK/files/1516911/partial.pdf)

Can you confirm that it works ?
It can't test it but I need multi h264 decode for a future project...

**Comment by SiewHoon** [comment]
The document mention on is gstreamer-vaapi plugin using open source media driver. This gst-msdk plugin is using MSDK library. Totally different two media stack software. Are you facing the issue of run multiple H264 decode stream?

**Comment by araani** [comment]
I will close the issue and evaluate multi-stream H264 using the proper embedded MSDK...
