### ISSUE TITLE
[master] libgstmfx plugin not installed in gstreamer plugins directory

### ISSUE THREAD

**Issue by uartie** [intel/gstreamer-media-SDK#54]
The gstmfx install target (libgstmfx.so) is currently installed directly into CMAKE_INSTALL_PREFIX.  In order for gstreamer tools to detect it automatically, it needs to be installed into the gstreamer plugins directory instead.

The gstreamer plugins directory can be found with pkg-config: `pkg-config --variable=pluginsdir gstreamer-1.0`.  Starting in CMAKE version 3.4.3, you can use `pkg_get_variable` (https://cmake.org/cmake/help/v3.4/module/FindPkgConfig.html) to get the `pluginsdir` value.  In earlier versions of CMAKE, you'll have to parse pkg-config output directly.  I would recommend updating cmake list scripts to require at least 3.4.3 for simplicity.

**Comment by uartie** [comment]
Upon further thought, it's probably better to install in <libdir>/gstreamer-1.0 (same as meson does on other branch).  This way, when user sets a custom install prefix, it will be honored accordingly.

**Comment by feiwan1** [comment]
@uartie, Could you help to review the patch for this issue:
https://github.com/intel/gstreamer-media-SDK/pull/66 
Thanks.

**Comment by feiwan1** [comment]
@uartie, Could you help to review the patch for this issue:
#66
Thanks.

**Comment by eero-t** [comment]
This 2017 bug is still not fixed (in Meson build).

> Upon further thought, it's probably better to install in <libdir>/gstreamer-1.0 (same as meson does on other branch). This way, when user sets a custom install prefix, it will be honored accordingly.

It should be libdir/gstreamer-{apiversion}/, if multiple GST API versions are supported.

Another reason for NOT putting plugins directly into generic library directory is that GST needs to scan all the libraries in that directory to find out which of them are its plugins / update GST registry cache.  That's a lot of redundant work needed at Gstreamer program startup.
