### ISSUE TITLE
[master] Use pkgconfig to find MFX library

### ISSUE THREAD

**Issue by uartie** [intel/gstreamer-media-SDK#55]
https://github.com/Intel-Media-SDK/MediaSDK provides a pkg-config (mfx.pc) file upon install for the MFX library.   In `cmake/FindMediaSDK.cmake`, please consider adding an additional option to find the mfx library via pkg_check_modules function.

**Comment by uartie** [comment]
Cool, I'll give it a try...

Are there plans to merge this branch to master in the near future?

**Comment by ishmael1985** [comment]
Can't give hard commitments on the timeline, it should happen within the next 2 quarters, but this is up to the discretion of the maintainers.

https://github.com/intel/gstreamer-media-SDK/issues/49

**Comment by SiewHoon** [comment]
Hi Artie,

Master branch currently also supported in use meson and ninja as well. 

For https://github.com/intel/gstreamer-media-SDK/tree/topic_linux_and_window, please discuss internally. Thank you.

**Comment by uartie** [comment]
@SiewHoon yep... unfortunately the meson build on master still forces me to use MFX_HOME to find MFX library.  The topic_linux_and_window appears to find it correctly with pkgconfig.  I'd prefer to not use MFX_HOME hackery.

**Comment by feiwan1** [comment]
@uartie, Could you help to review the patch for this issue:
#66
Thanks.

**Comment by SiewHoon** [comment]
Build command on target machine:
1. mkdir builddir && cd builddir
2. cmake .. -DUSE_VP9_DECODER=ON && make -j4
3. make install

The libgstmfx.so install in wrong location.

Install the project...
-- Install configuration: "release"
-- Installing: /usr/lib/gstreamer-1.0/lib/gstreamer-1.0/libgstmfx.so
-- Set runtime path of "/usr/lib/gstreamer-1.0/lib/gstreamer-1.0/libgstmfx.so" to "/usr/lib/gstreamer-1.0"
root@intel-corei7-64:~/fei/gstreamer-media-SDK/builddir# make install
[100%] Built target gstmfx
Install the project...
-- Install configuration: "release"
-- Up-to-date: /usr/lib/gstreamer-1.0/lib/gstreamer-1.0/libgstmfx.so
