### ISSUE TITLE
[master] VC1 video decoder fail to play for  not VC1 advance Profile with mkv, avi and mp4 file container format

### ISSUE THREAD

**Issue by SiewHoon** [intel/gstreamer-media-SDK#65]
command: gst-play-1.0 <File_Name> --audiosink='alsasink device=entertainment_main' --videosink=mfxsink".

- MP4:
aac_vc1_2ch_44100hz_1920x_1080y.mp4
mp3_vc1_2ch_44100hz_1920x_1080y.mp4
ogg_vc1_2ch_44100hz_1920x_1080y.mp4

- MKV:
aac_wmv_2ch_44100hz_1280x_1080y.mkv
mp3_wmv_2ch_44100hz_1280x_1080y.mkv
ogg_wmv_2ch_44100hz_1280x_1080y.mkv
pcm_wmv_2ch_44100hz_1280x_1080y.mkv
wma_wmv_2ch_44100hz_1280x_1080y.mkv

- AVI:
aac_wmv_2ch_44100hz_1280x_720y.avi
mp3_wmv_2ch_44100hz_1280x_720y.avi
ogg_wmv_2ch_44100hz_1280x_720y.avi
pcm_wmv_2ch_44100hz_1280x_720y.avi
wma_wmv_2ch_44100hz_1280x_720y.avi

Failed to play VC1 decoder.

**Comment by ishmael1985** [comment]
Can't this fix be proposed for porting to vc1parse in gst-plugins-bad mainline?
