### ISSUE TITLE
Does it support intra-refresh?

### ISSUE THREAD

**Issue by hxl-dy** [intel/gstreamer-media-SDK#67]
> x264 is able to use Periodic **_Intra Refresh_** instead of keyframes, which enables each frame to be capped to the same size enabling each slice to be immediately transmitted in a single UDP or TCP packet and on arrival immediately decoded.[15] Periodic Intra Refresh can replace keyframes by using a column of intra blocks that move across the video from one side to the other, thereby "refreshing" the image. In effect, instead of a big keyframe, the keyframe is "spread" over many frames. The video is still seekable: a special header, called the SEI Recovery Point, tells the decoder to "start here, decode X frames, and then start displaying the video." This hides the refresh effect from the user while the frame loads. Motion vectors are restricted so that blocks on one side of the refresh column don't reference blocks on the other side, effectively creating a demarcation line in each frame.
refer from: https://en.wikipedia.org/wiki/X264#Capabilities

**Comment by SiewHoon** [comment]
Are you referring to H264 encode infra-refresh? We do not support for H264 Encode intra-refresh.

**Comment by SiewHoon** [comment]
Proposed to closed its.
