### ISSUE TITLE
[topic lin & win] clean up all compilation warning message

### ISSUE THREAD

**Issue by SiewHoon** [intel/gstreamer-media-SDK#80]
@ishmael1985  , please help fix all the build warning in topic branch?

**Comment by ishmael1985** [comment]
You're talking about the GLib macro warnings? I think I can, somewhat tedious work though, would need some help :)

**Comment by kuhanh91** [comment]
Yeah, the GLib macro G_DECLARE_FINAL_TYPE causes a lot of warnings for the generic function glib_autoptr_cleanup_

What kind of help you need?

**Comment by ishmael1985** [comment]
Once I get the correct template to remove the warnings for a few files, would need to replicate them across the entire codebase :)

**Comment by SiewHoon** [comment]
Not just Glib macro only, also compilation warning complain on unused variable as well. All the build warning include the unused variable complain by compiler. You can refactor the code to avoid this kind build warning as well.

**Comment by kuhanh91** [comment]
Thanks, I can help to replicate them if you have managed to remove the warnings for a few files. I am stuck on trying to resolve this.

**Comment by ishmael1985** [comment]
Sure. I'll help out.

**Comment by ishmael1985** [comment]
It's done, all compilation warnings don't exist when building on Linux anymore. Moreover, it's now part of the PR.

**Comment by ishmael1985** [comment]
Please close this issue since this issue has been resolved.
