### ISSUE TITLE
Can't build gstreamer-media-SDK upon https://github.com/Intel-Media-SDK/MediaSDK on Ubuntu

### ISSUE THREAD

**Issue by xhaihao** [intel/gstreamer-media-SDK#83]
The default install path for mfx libraries is /opt/intel/mediasdk/lib/, however /opt/intel/mediasdk/lib/lin_x64/libmfx.a is required when building gstreamer-media-SDK.

**Comment by ishmael1985** [comment]
@xhaihao, please close if this issue has already been resolved.

**Comment by SiewHoon** [comment]
Hi @xhaihao 
What you need to build the gst-mfx in ubuntu, you need to 

export PKG_CONFIG_PATH="/usr/lib/pkgconfig:/usr/lib/x86_64-linux-gnu/pkgconfig:/opt/intel/mediasdk/lib/pkgconfig".

I will close this issue. If you still facing issue, please let me know or check with Fei.
